routes/web.php
        Route::get('roles/assign-permission/{id}', ['uses' => 'GymAdminManageRolesController@assignPermission', 'as' => 'gymmerchantroles.assign-permission']);
        Route::post('roles/assign-permission-store/{id}', ['uses' => 'GymAdminManageRolesController@assignPermissionStore', 'as' => 'gymmerchantroles.assign-permission-store']);
        Route::resource('gymmerchantroles', 'GymAdminManageRolesController');

        // Gym software Email promotion
        Route::get('email-promotion/preview-template/{id}', ['uses' => 'GymEmailPromotionController@previewTemplate', 'as' => 'email-promotion.preview-template']);
        Route::get('email-promotion/view-campaign/{id}', ['uses' => 'GymEmailPromotionController@viewCampaign', 'as' => 'email-promotion.view-campaign']);
        Route::get('email-promotion/edit-campaign/{id}', ['uses' => 'GymEmailPromotionController@editCampaign', 'as' => 'email-promotion.edit-campaign']);
        Route::get('email-promotion/ajax-promotions', ['uses' => 'GymEmailPromotionController@ajaxCreate', 'as' => 'email-promotion.ajax-promotions']);
        Route::post('email-promotion/send-promotion', ['uses' => 'GymEmailPromotionController@sendPromotion', 'as' => 'email-promotion.sendPromotion']);
        Route::resource('email-promotion', 'GymEmailPromotionController');


        // Generate I-card
        Route::get('client-list/{filter}', ['uses' => 'GymIdentityCardController@clientList', 'as' => 'i-card.clientList']);
        Route::post('email-qr-code', ['uses' => 'GymIdentityCardController@emailQrCode', 'as' => 'i-card.email-qr-code']);
        Route::resource('i-card', 'GymIdentityCardController');

        // Ace Tutorial
        Route::resource('tutorial', 'GymAdminTutorialController');

        Route::get('agreement', ['as' => "agreement", 'uses' => 'AgreementController@index']);


        //Gym Admin GymExpense Management Controller
        Route::get('remove-expense-modal/{ID}', ['uses' => 'GymAdminExpenseManagementController@removeExpense', 'as' => 'remove-expense-modal']);
        Route::get('get-expense', ['uses' => 'GymAdminExpenseManagementController@getExpense', 'as' => 'expense.get-expense']);
        Route::resource('expense', 'GymAdminExpenseManagementController');

        // Gestion de Ejercicios
        Route::resource('ejercicios', 'EjercicioController');

        // Gestion de Rutinas
        Route::resource('rutinas', 'RutinaController');

        // Gestion de la Galeria
        Route::resource('galeria', 'GaleriaController');

        //Task Management Routes
        Route::get('task/loadmoretask', ['as' => 'task.loadmoretask', 'uses' => 'GymAdminTaskManagementController@loadMoreTask']);
        Route::resource('task', 'GymAdminTaskManagementController', ['except' => 'create', 'show']);

        //Balance Report Routes
        Route::resource('balance-report', 'GymBalanceReportController');

            //region Super Admin Routes
            Route::get('superadmin/get-data', ['as' => 'superadmin.getData', 'uses' => 'GymSuperAdminController@getData']);
            Route::get('superadmin/dashboard', ['as' => 'superadmin.dashboard', 'uses' => 'GymSuperAdminController@showDashboard']);
            Route::get('superadmin/branch/{id?}', ['as' => 'superadmin.branch', 'uses' => 'GymSuperAdminController@branchPage']);
            Route::post('superadmin/store-branch', ['as' => 'superadmin.storeBranchPage', 'uses' => 'GymSuperAdminController@storeBranchPage']);
            Route::get('superadmin/manager/{id?}', ['as' => 'superadmin.manager', 'uses' => 'GymSuperAdminController@managerPage']);
            Route::post('superadmin/store-manager', ['as' => 'superadmin.storeManagerPage', 'uses' => 'GymSuperAdminController@storeManagerPage']);
            Route::get('superadmin/role/{id?}', ['as' => 'superadmin.role', 'uses' => 'GymSuperAdminController@rolePage']);
            Route::post('superadmin/store-role', ['as' => 'superadmin.storeRolePage', 'uses' => 'GymSuperAdminController@storeRolePage']);
            Route::get('superadmin/permission/{id?}', ['as' => 'superadmin.permission', 'uses' => 'GymSuperAdminController@permissionPage']);
            Route::post('superadmin/store-permission', ['as' => 'superadmin.storePermissionPage', 'uses' => 'GymSuperAdminController@storePermissionPage']);
            Route::get('superadmin/complete', ['as' => 'superadmin.complete', 'uses' => 'GymSuperAdminController@completePage']);
            Route::post('superadmin/set-business-id/{id?}', ['as' => 'superadmin.setBusinessId', 'uses' => 'GymSuperAdminController@setBusinessId']);
            Route::post('superadmin/update-role-and-permission', ['as' => 'superadmin.updateRolesAndPermissionPage', 'uses' => 'GymSuperAdminController@updateRolesAndPermissionPage']);
            Route::get('superadmin/get-earning-chart-data', ['as' => 'superadmin.getEarningChartData', 'uses' => 'GymSuperAdminController@getEarningChartData']);
            Route::get('superadmin/get-client-chart-data', ['as' => 'superadmin.getClientChartData', 'uses' => 'GymSuperAdminController@getClientChartData']);
            Route::resource('superadmin', 'GymSuperAdminController');
            //endregion

            //region message routes
            Route::resource('message', 'GymAdminMessageController', ['except' => ['edit', 'destroy']]);
            //endregion
        }
        );
    //endregion

    Route::get('qr-check-in/{url}', ['uses' => 'GymQrCheckinController@qrCodeCheckIn', 'as' => 'gym-qr-check-in']);

    //region customer routes
    Route::group(
        ['namespace' => 'Customer'], function () {
            Route::post('customer/reset-password', ['as' => 'customer.send-reset-link', 'uses' => 'CustomerController@sendResetPasswordLink']);
            Route::get('customer/reset/{token}', ['as' => 'customer.reset-password', 'uses' => 'CustomerController@resetPassword']);
            Route::post('customer/update-password', ['as' => 'customer.update-password', 'uses' => 'CustomerController@updatePassword']);
            Route::post('customer/register-store', ['as' => 'customer.register-store', 'uses' => 'CustomerController@registerStore']);
            Route::get('customer/register', ['as' => 'customer.register','uses' => 'CustomerController@register']);
            Route::get('customer/{provider}/{id?}', ['as' => 'customer.social-login', 'uses' => 'CustomerController@redirectToProvider']);
            Route::get('customer/{provider}/callback', ['uses' => 'CustomerController@handleProviderCallback']);
            Route::resource('customer', 'CustomerController', ['only' => ['index', 'store']]);

            Route::group(
                ['prefix' => 'customer-app', 'as' => 'customer-app.', 'middleware' => ['customer.auth', 'revalidate']], function () {
                    Route::get('logout', ['as' => 'logout', 'uses' => 'CustomerController@customerLogout']);

                    //region dashboard routes
                    Route::post('markRead', ['as' => 'dashboard.markRead', 'uses' => 'CustomerDashboardController@markRead']);
                    Route::resource('dashboard', 'CustomerDashboardController', ['only' => ['index']]);
                    //endregion

                    //region profile routes
                    Route::post('profile/upload-webcam-image/{id?}', ['as' => 'profile.upload-webcam-image', 'uses' => 'CustomerProfileController@uploadWebcamImage']);
                    Route::post('profile/upload-image',['as' => 'profile.upload-image', 'uses' => 'CustomerProfileController@uploadImage']);
                    Route::resource('profile', 'CustomerProfileController', ['only' => ['index', 'store']]);
                    //endregion

                    Route::get('rutinas/show/{id}', 'CustomerRutinaController@show');
                    Route::get('rutinas/asignar/{id}', 'CustomerRutinaController@asignarRutina');
                    Route::get('rutinas/rutinas', 'CustomerRutinaController@listadoRutinas');
                    Route::resource('rutinas', 'CustomerRutinaController');

                    Route::resource('galeria', 'CustomerGaleriaController');

                    //region subscriptions routes
                    Route::get('manage-subscription/get-membership', ['as' => 'manage-subscription.get-membership', 'uses' => 'CustomerManageSubscriptionController@getMembership']);
                    Route::get('manage-subscription/get-membership-amount', ['as' => 'manage-subscription.get-membership-amount', 'uses' => 'CustomerManageSubscriptionController@getMembershipAmount']);
                    Route::get('manage-subscription/get-data', ['as' => 'manage-subscription.get-data', 'uses' => 'CustomerManageSubscriptionController@getData']);
                    Route::resource('manage-subscription', 'CustomerManageSubscriptionController', ['except' => ['edit', 'update']]);
                    //endregion

                    //region payments routes
                    Route::get('payments/due-payments', ['as' => 'payments.due-payments', 'uses' => 'CustomerPaymentController@duePayments']);
                    Route::get('payments/get-due-payment-data', ['as' => 'payments.get-due-payment-data', 'uses' => 'CustomerPaymentController@getDuePaymentData']);
                    Route::get('payments/get-payment-data', ['as' => 'payments.get-payment-data', 'uses' => 'CustomerPaymentController@getPaymentData']);
                    Route::get('payments/download-invoice/{id}', ['as' => 'payments.download-invoice', 'uses' => 'CustomerPaymentController@downloadInvoice']);
                    Route::resource('payments', 'CustomerPaymentController', ['only' => ['index']]);
                    //endregion

                    //region attendance routes
                    Route::resource('attendance', 'CustomerAttendanceController', ['only' => ['index']]);
                    //endregion

                    //region message routes

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    protected $table = 'messages';

    protected $fillable = ['customer_id', 'merchant_id', 'to', 'from', 'text'];
}

resources/views/customer-app/message/create.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title" id="myLargeModalLabel">Nuevo Mensaje</h4>
</div>
<div class="modal-body">
    <div class="portlet-body">
        {!! Form::open(['route'=>'customer-app.message.store','id'=>'composeMailForm','class'=>'ajax-form form-material form-horizontal','method'=>'POST']) !!}
            <div class="form-group">
                <label class="col-sm-12">Seleccionar Destinatario</label>
                <div class="col-sm-12">
                    <select class="form-control select2" name="admin_id" id="admin_id">
                        <option selected disabled>Seleccionar Destinatario</option>
                        @foreach($admins as $admin)
                            <option value="{{ $admin->id }}">{{ $admin->first_name.' '.$admin->last_name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group">
                <textarea class="textarea_editor form-control" rows="15" placeholder="Ingresar texto ..."></textarea>
            </div>
        {!! Form::close() !!}
    </div>
</div>
<hr>
<div class="modal-footer">
    <button type="button" id="send-mail" class="btn btn-success">Enviar</button>
    <button type="button" class="btn default" data-dismiss="modal">Cerrar</button>
</div>
<script>
    $(function() {
        $('.textarea_editor').wysihtml5();
    });

    $('#send-mail').on('click', function () {
        var text = $('.textarea_editor').val();
        var admin_id = $('#admin_id').val();
        $.easyAjax({
            type: 'POST',
            url: '{{ route('customer-app.message.store') }}',
            data: {
                text: text,
                admin_id: admin_id
            },
            success: function (response) {
                $('#customerShowModal').modal("hide");
            }
        });
    });
</script>

resources/views/customer-app/message/index.blade.php
@extends('layouts.customer-app.basic')

@section('title')
    Fitsigma | Customer Message
@endsection

@section('CSS')
{!! HTML::style('fitsigma_customer/bower_components/html5-editor/bootstrap-wysihtml5.css') !!}
@endsection

@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Mensajes</h4>
        </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li>Menú Principal</li>
                <li class="active">Mensajes</li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <div class="row">
        <!-- Left sidebar -->
        <div class="col-md-12">
            <div class="white-box">
                <!-- row -->
                <div class="row">
                    <div class="col-lg-2 col-md-3  col-sm-12 col-xs-12 inbox-panel">
                        <div> <a href="javascript:;" class="btn btn-custom btn-block waves-effect waves-light compose-mail">Nuevo</a>
                            <div class="list-group mail-list m-t-20"> <a href="javascript:;" class="list-group-item active">Inbox <span class="label label-rouded label-success pull-right">@if(isset($unreadMessages) && $unreadMessages > 0) {{ $unreadMessages }} @endif</span></a>  </div>
                        </div>
                    </div>
                    <div class="col-lg-10 col-md-9 col-sm-12 col-xs-12 mail_listing">
                        <div class="inbox-center">
                            <table class="table table-hover">
                                <tbody>
                                @foreach($messages as $message)
                                    <tr @if(isset($unreadMessages) && $unreadMessages > 0 && $message->mark_as == 'unread')class="unread"@endif>
                                        <td class="hidden-xs">{{ $message->merchant->first_name }}</td>
                                        <td class="max-texts"> <a href="{{ route('customer-app.message.show', [$message->thread_id]) }}" /><!--<span class="label label-info m-r-10">Work</span>-->{{ substr($message->text, 0, 80) }}... </td>
                                        </td>
                                        <td class="text-right"> {{ \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $message->created_at)->diffForHumans() }} </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div>
        </div>
    </div>
@endsection

@section('JS')
    {!! HTML::script('fitsigma_customer/bower_components/html5-editor/wysihtml5-0.3.0.js') !!}
    {!! HTML::script('fitsigma_customer/bower_components/html5-editor/bootstrap-wysihtml5.js') !!}
<script>
    $('.compose-mail').on('click', function () {
        var url = '{{ route('customer-app.message.create') }}';
        $.ajaxModal('#customerShowModal', url);
    });
</script>
@endsection

resources/views/customer-app/message/show.blade.php
@extends('layouts.customer-app.basic')

@section('title')
    Improve | Detalles Mensaje
@endsection

@section('CSS')
{!! HTML::style('fitsigma_customer/bower_components/html5-editor/bootstrap-wysihtml5.css') !!}
<style>
    .padding-button {
        padding-left: 22px;
    }
    .margin-bottom-compose {
        margin-bottom: 18px;
    }
</style>
@endsection

@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Mensaje</h4>
        </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li>Menú Principal</li>
                <li class="active">Mensaje</li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <div class="chat-main-box">
        <!-- .chat-left-panel -->
        <div class="chat-left-aside">
            <div class="open-panel"><i class="ti-angle-right"></i></div>
            <div class="chat-left-inner inbox-panel">
                <div class="">
                    <div class="list-group mail-list m-t-20 padding-button">
                        <a href="{{ route('customer-app.message.create') }}" class="btn btn-custom btn-block waves-effect waves-light margin-bottom-compose compose-mail">Nuevo</a>
                        <a href="{{ route('customer-app.message.index') }}" class="list-group-item active">Inbox <span class="label label-rouded label-success pull-right">@if($unreadMessages > 0) {{ $unreadMessages }} @endif</span></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- .chat-left-panel -->
        <!-- .chat-right-panel -->
        <div class="chat-right-aside">
            <div class="chat-main-header">
                <div class="p-20 b-b">
                    <h3 class="box-title">Chat</h3>
                </div>
            </div>
            <div class="chat-box">
                <ul class="chat-list slimscroll p-t-30" id="message-chat">
                    @foreach($messages as $message)
                        <li @if($message->to == 'merchant') class="odd" @endif>
                            <div class="chat-body">
                                <div class="chat-text">
                                    <h4>@if($message->to == 'merchant') {{ $message->client->first_name.' '.$message->client->last_name }} @else {{ $message->merchant->first_name.' '.$message->merchant->last_name }} @endif</h4>
                                    <p> {!! nl2br($message->text) !!} </p>
                                    <b>{{ \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $message->created_at)->diffForHumans() }}</b> </div>
                            </div>
                        </li>
                    @endforeach
                </ul>
                <div class="row send-chat-box">
                    <div class="col-sm-12">
                        <textarea class="form-control" id="message" placeholder="Escribe tu mensaje"></textarea>
                        <div class="custom-send">
                            <button class="btn btn-danger btn-rounded" id="sendMail" type="button">Enviar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- .chat-right-panel -->
    </div>
@endsection

@section('JS')
{!! HTML::script('fitsigma_customer/js/chat.js') !!}
{!! HTML::script('fitsigma_customer/js/jquery.slimscroll.js') !!}
{!! HTML::script('fitsigma_customer/bower_components/html5-editor/wysihtml5-0.3.0.js') !!}
{!! HTML::script('fitsigma_customer/bower_components/html5-editor/bootstrap-wysihtml5.js') !!}
    <script>
        $(function () {
            $('.chat-list').animate({
                scrollTop: $('.chat-box li:last-child').position().top
            }, 'slow');
        });

        $('#sendMail').on('click', function () {
            var message = $('#message').val();
            var url = window.location.pathname;
            var id = url.substring(url.lastIndexOf('/') + 1);
            var updateUrl = '{{ route('customer-app.message.update', ['#id']) }}';
            var finalUrl = updateUrl.replace('#id', id);
            $.easyAjax({
                type: 'PUT',
                url: finalUrl,
                data: {
                    message: message
                },
                success: function (response) {
                    var str = '<li class="odd">'+
                                    '<div class="chat-body">'+
                                        '<div class="chat-text">'+
                                        '<h4>{{ $customerValues->first_name.' '.$customerValues->last_name }}</h4>'+
                                        '<p>' + response.message + '</p>'+
                                        '<b>few seconds ago</b> </div>'+
                                    '</div>'+
                                '</li>';
                    $( ".chat-list" ).append(str);
                    $('#message').val('');
                    $('.chat-list').stop().animate({
                        scrollTop: $(".chat-list")[0].scrollHeight
                    }, 800);
                }
            });
        });

        $('.compose-mail').on('click', function (event) {
            event.preventDefault();
            var url = '{{ route('customer-app.message.create') }}';
            $.ajaxModal('#customerShowModal', url);
        });
    </script>
@endsection