routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web']], function () {

    Route::get('/', function () {
     //   return redirect(url('customer'));
        return view('index');
    });

    //region routes for merchant panel
    Route::group(
        ['namespace' => 'Merchant', 'as' => 'merchant.'], function () {

        Route::get("/dashboard", "MerchantsController@dashboard");
        Route::get("/appointments", "MerchantsController@appointments");
        Route::get("/feedbacks", "MerchantsController@feedbacks");
        Route::get("/departments", "MerchantsController@departments");
        Route::get("/services", "MerchantsController@services");
        Route::get("/payments", "MerchantsController@payments");

        // Login resource controller
        Route::post('reset-password', ['as' => 'login.send-reset-link', 'uses' => 'MerchantsController@sendResetPasswordLink']);
        Route::get('reset/{token}', ['as' => 'login.reset-password', 'uses' => 'MerchantsController@resetPassword']);
        Route::post('update-password', ['as' => 'login.update-password', 'uses' => 'MerchantsController@updatePassword']);
        Route::resource('login', 'MerchantsController', ['only' => ['index', 'store']]);

        Route::get('lock-screen', ['uses' => 'LockScreenController@get', 'as' => 'lockscreen']);
        Route::get('keep-alive', ['uses' => 'LockScreenController@keepAlive', 'as' => 'keep-alive']);
        Route::post('lock-login', ['uses' => 'LockScreenController@post', 'as' => 'lockLogin']);
        Route::get('logout', ['uses' => 'LockScreenController@logout', 'as' => 'logout']);

    }
    );
    //endregion

    //region gym merchant admin routes
    Route::group(
        ['prefix' => 'gym-admin', 'middleware' => ['merchant.auth', 'revalidate'], 'namespace' => 'GymAdmin', 'as'=>'gym-admin.'], function () {

        // Admin Gym Dashboard Controlller

        // Mark read notifications
        Route::post('markRead', ['as' => 'dashboard.markRead', 'uses' => 'AdminGymDashboardController@markRead']);
        Route::resource('dashboard', 'AdminGymDashboardController', ['only' => ['index', 'markRead']]);

        // Gym Admin Logout Controller

        Route::resource('logout', 'GymAdminLogoutController', ['only' => ['index']]);

        // Gym Admin Base Controller

        Route::get('client/index', ['uses' => 'AdminGymClientsController@index', 'as' => 'client.index']);
        Route::get('client/create', ['uses' => 'AdminGymClientsController@create', 'as' => 'client.create']);
        Route::get('client/show/{ID}', ['uses' => 'AdminGymClientsController@show', 'as' => 'client.show']);
        Route::post('client/store', ['uses' => 'AdminGymClientsController@store', 'as' => 'client.store']);
        Route::post('client/update', ['uses' => 'AdminGymClientsController@update', 'as' => 'client.update']);
        Route::get('client/ajax_create', ['uses' => 'AdminGymClientsController@ajax_create', 'as' => 'client.ajax_create']);
        Route::get('client/remove/modal/{ID}', ['uses' => 'AdminGymClientsController@removeClient', 'as' => 'remove.modal']);
        Route::get('client/calendar/{ID}', ['uses' => 'AdminGymClientsController@calender', 'as' => 'client.calender']);
        Route::get('client/ajax/payments/{ID}', ['uses' => 'AdminGymClientsController@ajax_create_payments', 'as' => 'client.ajax-payments']);
        Route::post('client/save-webcam-image/{id}', ['as' => 'client.save-webcam-image', 'uses' => 'AdminGymClientsController@saveWebCamImage']);
        Route::get('client/remove/{ID}', ['uses' => 'AdminGymClientsController@destroy', 'as' => 'client.destroy']);
        Route::post('gymclient/uploadimage', ['as' => 'gymclient.uploadimage', 'uses' => 'AdminGymClientsController@uploadImage']);
        Route::get('register-enquiry/{ID}', ['uses' => 'AdminGymClientsController@registerEnquiry', 'as' => 'client.register-enquiry']);
        Route::get('client/import', ['uses' => 'AdminGymClientsController@import', 'as' => 'client.import']);
        Route::post('client/import', ['uses' => 'AdminGymClientsController@importUpload', 'as' => 'client.importUpload']);
        Route::get('client/import/match', ['uses' => 'AdminGymClientsController@match', 'as' => 'client.match']);
        Route::post('client/import/process', ['as' => 'client.importProcess', 'uses' => 'AdminGymClientsController@importProcess']);
        Route::post('client/import/checkStatus', ['as' => 'client.checkImportProgress', 'uses' => 'AdminGymClientsController@checkImportProgress']);
        Route::post('client/import/cancel', ['as' => 'client.cancelImport', 'uses' => 'AdminGymClientsController@cancelImport']);
        Route::get('client/import/failed_records', ['as' => 'client.failed_records', 'uses' => 'AdminGymClientsController@failedRecords']);
        Route::get('client/import/downloadFailedRecords', ['as' => 'client.downloadFailedRecords', 'uses' => 'AdminGymClientsController@downloadFailedRecords']);

        // Gym Enquiry Controller
        Route::get('enquiry/index', ['uses' => 'GymEnquiryController@index', 'as' => 'enquiry.index']);
        Route::get('enquiry/ajax/create', ['uses' => 'GymEnquiryController@ajaxCreate', 'as' => 'enquiry.create.ajax']);
        Route::get('enquiry/remove/modal/{ID}', ['uses' => 'GymEnquiryController@removeEnquiry', 'as' => 'enquiry.modal']);
        Route::get('enquiry/follow-modal/{ID}', ['uses' => 'GymEnquiryController@followModal', 'as' => 'enquiry.follow-modal']);
        Route::get('enquiry/view-follow-modal/{ID}', ['uses' => 'GymEnquiryController@viewFollowModal', 'as' => 'enquiry.view-follow-modal']);
        Route::post('enquiry/saveFollowUp', ['uses' => 'GymEnquiryController@saveFollowUp', 'as' => 'enquiry.saveFollowUp']);
        Route::resource('enquiry', 'GymEnquiryController');

        // Gym Setting
        Route::get('setting/mail', ['as' => 'setting.mail', 'uses' => 'GymAdminSettingController@mailPage']);
        Route::post('setting/store-mail-credentials', ['as' => 'setting.storeMailCredentials', 'uses' => 'GymAdminSettingController@storeMailCredentials']);
        Route::get('setting/file-upload', ['as' => 'setting.fileUpload', 'uses' => 'GymAdminSettingController@fileUploadPage']);
        Route::post('setting/store-file-upload-credentials', ['as' => 'setting.storeFileUploadCredentials', 'uses' => 'GymAdminSettingController@storeFileUploadCredentials']);
        Route::get('setting/others', ['as' => 'setting.others', 'uses' => 'GymAdminSettingController@othersPage']);
        Route::post('setting/store-others-setting-credentials', ['as' => 'setting.storeOtherSettingCredentials', 'uses' => 'GymAdminSettingController@storeOtherSettingCredentials']);
        Route::get('setting/footer', ['as' => 'setting.footer', 'uses' => 'GymAdminSettingController@footerPage']);
        Route::post('setting/store-footer-setting-credentials', ['as' => 'setting.storeFooterSettingCredentials', 'uses' => 'GymAdminSettingController@storeFooterSettingCredentials']);
        Route::post('gymsetting/image', ['as' => 'gymsetting.image', 'uses' => 'GymAdminSettingController@image']);
        Route::post('setting/front-image', ['as' => 'setting.frontImage', 'uses' => 'GymAdminSettingController@storeFrontImage']);
        Route::post('setting/customer-image', ['as' => 'setting.customerImage', 'uses' => 'GymAdminSettingController@storeCustomerImage']);

        Route::resource('setting', 'GymAdminSettingController');

        // Gym backup
        Route::get('backup/getbackup/{id}', ['uses' => 'GymAdminbackupController@getbackup', 'as' => 'backup.getbackup']);
        Route::resource('backup', 'GymAdminbackupController');

        // Software update
        Route::resource('upcoming', 'SoftwareUpdateController');

        // Gym Media Controller
        Route::get('media/ajax/create', ['uses' => 'GymMediaController@ajax_create', 'as' => 'media.ajax_create']);
        Route::resource('media', 'GymMediaController');

        // Gym membership resource
        Route::resource('membership', 'GymAdminMembershipController');

        // Gym Feedback Controller
        Route::get('feedback/', ['uses' => 'GymFeedbackController@index', 'as' => 'feedback.index']);
        Route::post('feedback/load/comments', ['uses' => 'GymFeedbackController@ajaxLoadComments', 'as' => 'feedback.load.comments']);
        Route::post('feedback/more/comments', ['uses' => 'GymFeedbackController@loadMoreComments', 'as' => 'feedback.more.comments']);
        Route::post('feedback/reply', ['uses' => 'GymFeedbackController@postReply', 'as' => 'feedback.reply.store']);

        Route::get('feedback/remove/modal/{ID}', ['uses' => 'GymFeedbackController@removeReply', 'as' => 'remove.reply']);
        Route::get('feedback/remove/reply/{ID}', ['uses' => 'GymFeedbackController@destroy', 'as' => 'feedback.destroy']);
        Route::post('feedback/edit/reply', ['uses' => 'GymFeedbackController@edit', 'as' => 'feedback.edit']);


        // Gym Offer Controller
        Route::get('offers/ajax/create', ['uses' => 'GymOfferMangeController@ajax_create', 'as' => 'offers.ajax_create']);
        Route::resource('offers', 'GymOfferMangeController');

        // Package resource
        Route::resource('package', 'GymAdminPackageController');

        // Gym Profile Controller
        Route::resource('profile', 'GymAdminProfileController');
        Route::post('gym/uploadimage', ['as' => 'gym.uploadimage', 'uses' => 'GymAdminProfileController@uploadImage']);

        // Gym Membership Payments

app/Http/Controllers/GymAdmin/AgreementController.php
<?php

namespace App\Http\Controllers\GymAdmin;

use Illuminate\Http\Request;

class AgreementController extends GymAdminBaseController
{
    public function __construct() {
        parent::__construct();
    }

    public function index(){
        return view('gym-admin.agreement.index', $this->data);
    }
}

app/Http/Controllers/GymAdmin/EjercicioController.php
<?php

namespace App\Http\Controllers\GymAdmin;

use App\Classes\Reply;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ImageController;
use App\Models\Ejercicio;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Auth;
use Session;

class EjercicioController extends GymAdminBaseController{

    public function index(){
        $this->data['ejercicios'] = Ejercicio::getEjercicios();

        $this->data['title'] = "Ejercicios";

        return View::make('gym-admin.ejercicios.index', $this->data);
    }

    public function create(){
        $this->data['title'] = "Agregar Ejercicio";

        return view('gym-admin.ejercicios.create', $this->data);
    }

    public function store(Request $request){
        $this->validate($request, [
    			'nombre' => 'required'
    		]);
        $requestData = $request->all();

        $nuevoEjercicio = new Ejercicio($requestData);

        $controllerImagen = new ImageController();
        $imagen_url = $controllerImagen->guardarImagenEjercicio($request);
        if($imagen_url != false){
            $nuevoEjercicio->archivo_url = $imagen_url;
        }

        $nuevoEjercicio->save();

        return Reply::redirect(route('gym-admin.ejercicios.index'), "Ejercicio guardado.");
    }

    public function show($id){
        $this->data['ejercicio'] = Ejercicio::findOrFail($id);
        $this->data['title'] = "Ver Ejercicio";

        return view('gym-admin.ejercicios.show', $this->data);
    }

    public function edit($id){
        $this->data['ejercicio'] = Ejercicio::findOrFail($id);
        $this->data['title'] = "Editar Ejercicio";

        return view('gym-admin.ejercicios.edit', $this->data);
    }

    public function update($id, Request $request){
        $ejercicio = Ejercicio::findOrFail($id);
        $this->validate($request, [
    			'nombre' => 'required'
    		]);
        $requestData = $request->all();

        $controllerImagen = new ImageController();
        $imagen_url = $controllerImagen->guardarImagenEjercicio($request);
        if($imagen_url != false){
            $requestData['archivo_url'] = $imagen_url;
        }

        $ejercicio->update($requestData);

      //  return Reply::redirect(route('gym-admin.ejercicios.index'), "Ejercicio actualizado.");
        return redirect('gym-admin/ejercicios');
    }

    public function destroy($id){
        Ejercicio::destroy($id);

        return Reply::redirect(route('gym-admin.ejercicios.index'), "Ejercicio eliminado.");
    }
}

app/Http/Controllers/GymAdmin/GaleriaController.php
<?php

namespace App\Http\Controllers\GymAdmin;

use App\Classes\Reply;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ImageController;
use App\Models\Galeria;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Auth;
use Session;

class GaleriaController extends GymAdminBaseController{

    public function index(){
        $this->data['archivos'] = Galeria::getArchivos();

        $this->data['title'] = "Galeria";

        return View::make('gym-admin.galeria.index', $this->data);
    }

    public function create(){
        $this->data['title'] = "Agregar Imagen";

        return view('gym-admin.galeria.create', $this->data);
    }

    public function store(Request $request){
        $requestData = $request->all();

        $nuevoArchivo = new Galeria($requestData);

        $controllerImagen = new ImageController();
        $imagen_url = $controllerImagen->guardarImagenGaleria($request);
        $nuevoArchivo->archivo_url = $imagen_url;

        $nuevoArchivo->save();

        return Reply::redirect(route('gym-admin.galeria.index'), "Archivo Guardado.");
    }

    public function show($id){
        $this->data['archivo'] = Galeria::findOrFail($id);
        $this->data['title'] = "Ver Archivo";

        return view('gym-admin.galeria.show', $this->data);
    }

    public function edit($id){
        $this->data['archivo'] = Galeria::findOrFail($id);
        $this->data['title'] = "Editar Archivo";

        return view('gym-admin.galeria.edit', $this->data);
    }

    public function update($id, Request $request){
        $archivo = Galeria::findOrFail($id);
        $requestData = $request->all();

        $controllerImagen = new ImageController();
        $imagen_url = $controllerImagen->guardarImagenGaleria($request);
        if($imagen_url != false){
            $requestData['archivo_url'] = $imagen_url;
        }

        $archivo->update($requestData);

      //  return Reply::redirect(route('gym-admin.ejercicios.index'), "Archivo Actualizado.");
        return redirect('gym-admin/galeria');
    }

    public function destroy($id){
        Galeria::destroy($id);

        return Reply::redirect(route('gym-admin.galeria.index'), "Archivo Eliminado.");
    }
}

app/Http/Controllers/GymAdmin/GymAdminLogoutController.php
<?php

namespace App\Http\Controllers\GymAdmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class GymAdminLogoutController extends Controller
{
    public function index()
    {
        Auth::guard('merchant')->logout();

        //remove business_id session
        if(Session::has('business_id')){
            Session::forget('business_id');
        }

        return Redirect::route('merchant.login.index');
    }
}

app/Http/Controllers/GymAdmin/GymAdminTutorialController.php
<?php

namespace App\Http\Controllers\GymAdmin;


use App\Models\GymTutorial;

class GymAdminTutorialController extends GymAdminBaseController
{

    public function index() {
        $this->data['title'] = "Improve.fit Tutoriales";
        $this->data['tutorials'] = GymTutorial::all();
        return view('gym-admin.tutorial.index', $this->data);
    }

    public function show($id) {
        $this->data['tutorial'] = GymTutorial::find($id);
        return view('gym-admin.tutorial.show', $this->data);
    }

}

resources/views/gym-admin/offers/index.blade.php
@extends('layouts.gym-merchant.gymbasic')

@section('CSS')
    {!! HTML::style('admin/global/plugins/ladda/ladda-themeless.min.css') !!}
    {!! HTML::style('admin/global/plugins/bootstrap-datepicker/css/datepicker.css') !!}
    {!! HTML::style('admin/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') !!}
    {!! HTML::style('admin/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css') !!}
    {!! HTML::style('admin/global/plugins/bootstrap-select/css/bootstrap-select.min.css') !!}
    {!! HTML::style('admin/global/plugins/datatables/datatables.min.css') !!}
    {!! HTML::style('admin/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css') !!}
@stop

@section('content')
    <div class="container-fluid"      >
        <!-- BEGIN PAGE BREADCRUMBS -->
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a href="{{route('gym-admin.dashboard.index')}}">Inicio</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Offers</span>
            </li>
        </ul>
        <!-- END PAGE BREADCRUMBS -->
        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="page-content-inner">
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="portlet light ">
                        <div class="portlet-title">
                            <div class="caption font-dark">
                                <i class="icon-present font-red"></i>
                                <span class="caption-subject font-red bold uppercase"> GYM-OFFERS</span>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="table-toolbar">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="btn-group">
                                            <a id="sample_editable_1_new" onclick="createModal()" class="btn sbold dark"> Agregar Nuevo
                                                <i class="fa fa-plus"></i>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                    </div>
                                </div>
                            </div>
                            <table style="width: 100%;" class="table table-striped table-bordered table-hover table-checkable order-column" id="gym_clients">
                                <thead>
                                <tr>
                                    <th class="max-desktop"> Title </th>
                                    <th class="desktop"> Valid From </th>
                                    <th class="desktop"> Valid Till </th>
                                    <th class="desktop"> Original Price </th>
                                    <th class="desktop"> Discounted Price </th>
                                    <th class="desktop"> Offer For </th>
                                    <th class="desktop"> Status </th>
                                    <th class="desktop"> Actions </th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    <!-- END EXAMPLE TABLE PORTLET-->
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
    {{--Modal Start--}}

    <div class="modal fade bs-modal-md in" id="gymOfferModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-md" id="modal-data-application">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <span class="caption-subject font-red-sunglo bold uppercase" id="modelHeading"></span>
                </div>
                <div class="modal-body">
                    Cargando...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn default" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn blue">Guardar cambios</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    {{--End Modal--}}
@stop

@section('footer')
    {!! HTML::script('admin/global/scripts/datatable.js') !!}
    {!! HTML::script('admin/pages/scripts/table-datatables-managed.js') !!}
    {!! HTML::script('admin/global/plugins/datatables/datatables.min.js') !!}
    {!! HTML::script('admin/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js') !!}
    {!! HTML::script('admin/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') !!}
    {!! HTML::style('admin/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') !!}
    {!! HTML::script('admin/pages/scripts/components-date-time-pickers.min.js') !!}
    {!! HTML::script('admin/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') !!}
    {!! HTML::script('admin/global/plugins/bootbox/bootbox.min.js') !!}
    {!! HTML::script('admin/global/plugins/bootstrap-select/js/bootstrap-select.min.js') !!}
    {!! HTML::script('admin/pages/scripts/components-bootstrap-select.min.js') !!}
    <script>

        var table = $('#gym_clients');

        // begin first table

        table.dataTable({
            responsive: true,
            "sAjaxSource":"{{ route('gym-admin.offers.ajax_create') }}",
            "aoColumns": [
                { 'sClass': 'center', "bSortable": true, "width": "20%", "bSearchable": true  },
                { 'sClass': 'center', "bSortable": true,  "bSearchable": true  },
                { 'sClass': 'center', "bSortable": true,  "bSearchable": true  },
                { 'sClass': 'center', "bSortable": true,  "bSearchable": true  },
                { 'sClass': 'center', "bSortable": true,  "bSearchable": true  },
                { 'sClass': 'center', "bSortable": true,  "bSearchable": true  },
                {'sClass': 'center', "bSortable": true, "bSearchable": true   },
                { 'sClass': 'center', "bSortable": false, "width": "10%",  "bSearchable": true }
            ],
            // Internationalisation. For more info refer to http://datatables.net/manual/i18n
            "language": {
                "aria": {
                    "sortAscending": ": activate to sort column ascending",
                    "sortDescending": ": activate to sort column descending"
                },
                "emptyTable": "No hay registros disponibles en la tabla",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "infoEmpty": "No se encontraron registros",
                "infoFiltered": "(filtered1 from _MAX_ total records)",
                "lengthMenu": "Mostrar _MENU_",
                "search": "Buscar:",
                "zeroRecords": "No se encontraron coincidencias",
                "paginate": {
                    "previous":"Anterior",
                    "next": "Siguente",
                    "last": "Ultimo",
                    "first": "Primero"
                }
            },

            // Or you can use remote translation file
            //"language": {
            //   url: '//cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Portuguese.json'
            //},

            // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
            // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
            // So when dropdowns used the scrollable div should be removed.
            "dom": "<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

            "bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.

            "columnDefs": [ {
                "targets": 0,
                "orderable": false,
                "searchable": false
            }],

            "lengthMenu": [
                [5, 15, 20, -1],
                [5, 15, 20, "Todos"] // change per page values here
            ],
            // set the initial value
            "pageLength": 5,
            "pagingType": "bootstrap_full_number",
            "columnDefs": [{  // set default column settings
                'orderable': false,
                'targets': [0]
            }, {
                "searchable": false,
                "targets": [0]
            }],
            "order": [
                [1, "asc"]
            ] // set first column as a default sort by asc
        });


        function createModal(){
            var url = '{{route('gym-admin.offers.create')}}';
            $('#modelHeading').html('Add Offer');
            $.ajaxModal("#gymOfferModal", url);
        }
    </script>
    <script>
        function editOffer(id)
        {
            var show_url = '{{route('gym-admin.offers.show',['#id'])}}';
            var url = show_url.replace('#id',id);
            $('#modelHeading').html('Edit Offer');
            $.ajaxModal('#gymOfferModal',url);
        }
    </script>
    <script>
        function Delete(id)
        {
            var offerID = id;

            bootbox.confirm({
                message: "Do you want to delete this offer?",
                buttons: {
                    confirm: {
                        label: "Yes",
                        className: "btn-primary"
                    }
                },
                callback: function(result){
                    if(result){

                        var url = '{{route('gym-admin.offers.destroy',':id')}}';
                        url = url.replace(':id',offerID);

                        $.easyAjax({
                            url: url,
                            type: "DELETE",
                            data: {offerID: offerID,_token: '{{ csrf_token() }}'},
                            success: function(){
                                $('#offer_'+id).fadeOut(500);

                            }
                        });
                    }
                    else {
                        console.log('cancel');
                    }
                }
            })
        }
    </script>
@stop